name: Test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-static-current:
    strategy:
      fail-fast: false
      matrix:
        puppet: [7.22.0]
        ruby: [2.7.7, 3.0.5, 3.1.3]

    name: Static code analysis
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        PUPPET_VERSION: ${{ matrix.puppet }}

    - name: Run metadata lint
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake metadata_lint

    - name: Run puppet lint
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake lint

    - name: Run puppet syntax check
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake syntax

    - name: Run puppet rspec tests
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} STRICT_VARIABLES=yes bundle exec rake spec

    - name: Run rubocop tests
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake rubocop

  test-static-old:
    strategy:
      fail-fast: false
      matrix:
        puppet: [5.5.22, 6.29.0]
        ruby: [2.5.9, 2.6.9]

    name: Static code analysis
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        PUPPET_VERSION: ${{ matrix.puppet }}

    - name: Run metadata lint
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake metadata_lint

    - name: Run puppet lint
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake lint

    - name: Run puppet syntax check
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake syntax

    - name: Run puppet rspec tests
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} STRICT_VARIABLES=yes bundle exec rake spec

    - name: Run rubocop tests
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake rubocop

  test-integration:
    strategy:
      fail-fast: false
      matrix:
        puppet: [puppet6, puppet7]
        beakerset: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, centos-7, debian-10, debian-11]

    name: Integration tests
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.9
        bundler-cache: true
      env:
        BEAKER_set: ${{ matrix.beakerset }}
        BEAKER_PUPPET_COLLECTION: ${{ matrix.puppet }}
        PUPPET_INSTALL_TYPE: agent

    - name: Run puppet-beaker tests
      run: |
        BEAKER_destroy=yes bundle exec rake acceptance
      env:
        BEAKER_set: ${{ matrix.beakerset }}
        BEAKER_PUPPET_COLLECTION: ${{ matrix.puppet }}
        PUPPET_INSTALL_TYPE: agent
